### PR TITLE
p2ce playerproxy changes

### PR DESCRIPTION
**Pull request by JJL772**
* Adds some inputs to the playerproxy for giving the player a paintgun, and long fall boots.
* Adds an item to equip long fall boots

### CODE REVIEW

**Review by braem — CHANGES_REQUESTED** [review]
`item_boots` should be added to visgroups.fgd as well

**Review by braem — CHANGES_REQUESTED** [review]
This one: https://github.com/ChaosInitiative/Chaos-FGD/blob/master/fgd/visgroups.cfg

**Comment by JJL772** [comment]
what the fuck I managed to lose my changes somehow???? sorry!

**Comment by JJL772** [comment]
Oh my god, I did an interactive rebase and amended a commit but forgot to add the change

**Review by braem — APPROVED** [review]

**Pull request merged**
