### PR TITLE
added partner KV to prop_weighted_cube.

### PR DESCRIPTION
**Pull request by Trico-Everfire**
Added partner KV to prop_weighted_cube. This is to link a Schrodinger's cube to a partner.

### CODE REVIEW

**Comment by TeamSpen210** [comment]
You might want to also add a `line(255 255 255, targetname, partner)` helper so that the connection is shown visually in Hammer.

**Comment by Luke18033** [comment]
Does this keyvalue actually work? I've never used or heard of it. Note that normally they automatically link together based on the order the entities spawn.

**Comment by TeamSpen210** [comment]
It's not an existing KV, this would be one planned to be added to CE?

**Comment by Luke18033** [comment]
Yep, this doesn't exist. Something like this is planned to be added, but whoever does that will just add it to the FGD themselves.

**Pull request closed without merging**
