### PR TITLE
Fix/linux

### PR DESCRIPTION
**Pull request by JJL772**
This fixes the linux build script.

### CODE REVIEW

**Review by braem — APPROVED** [review]
Woops! Fudged this a bit when I made it.

Keep in mind though that the FGD should always be built on windows for releases for now, as building it on linux misses a few things - this is why the linux action does not upload artifacts rn. Not entirely sure why it isn't identical to the windows build, or if it has been remedied in srctools since then.

**Comment by JJL772** [comment]
Does the FGD build properly on Linux at least? I've been using that from time to time. we don't use linux for CI other than actually compiling the engine

**Comment by JJL772** [comment]
just realized & was being used instead of &&
it seems to work, but it spawns a subshell where the first command is executed asynchronously in the background, not really good practice

**Comment by braem** [comment]
> 
> 
> Does the FGD build properly on Linux at least? I've been using that from time to time. we don't use linux for CI other than actually compiling the engine

Yeah they are pretty much identical, linux is just missing a few things. A couple of helper lines/spheres, not any fields looks like:
image

**Review by braem — APPROVED** [review]

**Comment by JJL772** [comment]
ewww crlf

**Review by Gocnak — APPROVED** [review]

**Pull request merged**
