### PR TITLE
Added Model and Skin support to info_player_start

### PR DESCRIPTION
**Pull request by Trico-Everfire**
there is also a commit for prop_weighted_cube, which was changed and then reverted back to it's original form, i wish i could exclude files from prs in github, too bad i don't fully know how this all works.

TLDR: only change made in this PR is Model and Skin support for info_player_start, as green gordon doesn't always put into perspective how the player would look in a map.

### CODE REVIEW

**Comment by JJL772** [comment]
You can squash commits using an interactive rebase, and then force push to the branch. 

I'm not sure that we'd want a skin for info_player_start anyway since it doesn't do anything in-game. If momentum or p2ce wants a custom info_player_start skin, we'd just override the mdl.

**Comment by Trico-Everfire** [comment]
> You can squash commits using an interactive rebase, and then force push to the branch.
> 
> I'm not sure that we'd want a skin for info_player_start anyway since it doesn't do anything in-game. If momentum or p2ce wants a custom info_player_start skin, we'd just override the mdl.

idk what that first thing means, i don't use git that often.

secondly: the "skin" (custom model option) is a QoL feature meant for mod makers who want to see their character(s) compared to the map they're making, sometimes it's hard to do with a green gordon freeman (it doesn't give much apart from a "sense of scale".) it's neat to have the option.

**Comment by braem** [comment]
> I'm not sure that we'd want a skin for info_player_start anyway since it doesn't do anything in-game. If momentum or p2ce wants a custom info_player_start skin, we'd just override the mdl.

I see this is done for personality cores and other things so im not totally against it. We can swap out the default one very easily per-game which is nice yeah.

------------
@Trico-Everfire 

Model and skin is all you'd want (remove skinset and setmodel base). 

Looks like this is including then reverting commits you had on your last PR (branch off of upstream/master next time) so these will have to be squashed/fixuped (look up an interactive rebase). Alternatively can just push more here and we can squash n' merge - just make sure youre only editing the playerstart file as another unrelated file is being edited here.

**Comment by JJL772** [comment]
In that case I'm not opposed to merging this in. Will wait for trico to rebase this though

**Review by JJL772 — APPROVED** [review]

**Comment by Gocnak** [comment]
> secondly: the "skin" (custom model option) is a QoL feature meant for mod makers who want to see their character(s) compared to the map they're making, sometimes it's hard to do with a green gordon freeman (it doesn't give much apart from a "sense of scale".) it's neat to have the option.

Pushing on this, how come a prop_dynamic or similar doesn't work?

**Review by Gocnak — CHANGES_REQUESTED** [review]
See above comment

**Pull request closed without merging**
