### PR TITLE
Add info_portal_gamerules

### PR DESCRIPTION
**Pull request by JJL772**
This should be merged after the internal PR is.

### CODE REVIEW

**Review by braem — CHANGES_REQUESTED** [review]
Also add to db/factories/p2ce.txt!

**Comment by TeamSpen210** [comment]
Note that file isn't meant to be directly edited, instead you use `dumpentityfactories`, so we can see entities only in the FGD but not ingame, or vice versa.

**Comment by braem** [comment]
> Note that file isn't meant to be directly edited, instead you use `dumpentityfactories`, so we can see entities only in the FGD but not ingame, or vice versa.

Oh! News to me. Thanks spen!

**Comment by JJL772** [comment]
I added it to the end of the factories, in a different PR I'll add the dumped version from the game since there are quite a few changes in it.

**Review by braem — APPROVED** [review]

**Comment by braem** [comment]
Is this blocked by something or good to go?

**Review by craftablescience — APPROVED** [review]

**Pull request merged**
