### PR TITLE
USE_AI Tag for AI entities

### PR DESCRIPTION
**Pull request by tmob03**
Also removed ai_addon and ai_addon_builder as they are left-overs from valve experiments not implemented in game but left in the FGD. Info_remarkable removed as it's very l4d focused like env_outtro_stats, can be removed from C++ in my opinion.

### CODE REVIEW

**Comment by AWildErin** [comment]
> Also removed ai_addon and ai_addon_builder as they are left-overs from valve experiments not implemented in game 
We do actually compile this entity in. Whether we should or not is another question, but it is something we have in Chaos.

**Comment by tmob03** [comment]
> We do actually compile both of them in. Granted `ai_addon_builder` is compiled when hl2 entities are. Whether we should or  > not is another question, but it is something we have in Chaos.

Oh, hmm didn't get either with `ent_info_datatable` in momentum mod, couldn't test in p2ce as I don't have it. Do they actually do anything? https://developer.valvesoftware.com/wiki/Ai_addon_builder The VDC page implies it's broken/not implemented as "This code has never been released to the public or used in its entirety in a Valve title."

**Comment by AWildErin** [comment]
Not sure if it's implemented fully, since we don't particularly use it, but I'm just letting you know that we do have them in Chaos, but I'm not sure if we're ever going to use it. So if the consensus is that we're going to remove them, the licensee can probably go ahead and remove them from C++ aswell

**Comment by braem** [comment]
I'd like to start conversation about whether `info_remarkable` and `ai_addon*` are used or even functional. If not then we can yeet em in the codebase. To get in all this other great work though it might be best to leave those to later and remove them when we have a decision.

**Comment by tmob03** [comment]
> I'd like to start conversation about whether `info_remarkable` and `ai_addon*` are used or even functional. If not then we can yeet em in the codebase. To get in all this other great work though it might be best to leave those to later and remove them when we have a decision.

[info_remarkable](https://developer.valvesoftware.com/wiki/Info_remarkable) is used, but only in l4d. It's very specific to l4d as far as I can tell, it's used to make survivors speak when looking at them.

[ai_addon entities](https://developer.valvesoftware.com/wiki/Ai_addon_builder) I doubt is used and I doubt functional, at least it hasn't been in any source game. Valve made it in 2007 early in development for Portal 2. It was part of Valve's "Directed Design Experiments" It was the 2nd of the experiments and it did this: "Their experiment consisted of Overwatch Soldiers having different chips on their uniforms that would activate abilities such as flying and super-speed. A player would shoot an enemy, who would be blown to pieces, but with a twist: Another enemy would then run over, find stray ability chips other soldiers would have dropped, and would upgrade their abilities on the spot." from: https://halflife.fandom.com/wiki/Directed_Design_Experiments

**Comment by tmob03** [comment]
Fixed merge conflicts ^

**Review by braem — APPROVED** [review]
Going to approve this but I'd like someone from P2CE to confirm they won't want to keep em around.

**Comment by tmob03** [comment]
@braem Before this gets merged, are npcs planned at all in momentum's campaign/learn section? Some things I wasn't sure on adding into `USE_AI` was scripted_sentence, scripted_sequence, logic_chreographed_scene, etc. Animation entities that can control NPC animations and dialogue.

**Comment by braem** [comment]
> @braem Before this gets merged, are npcs planned at all in momentum's campaign/learn section? Some things I wasn't sure on adding into `USE_AI` was scripted_sentence, scripted_sequence, logic_chreographed_scene, etc. Animation entities that can control NPC animations and dialogue.

Definitely not in learn. I'm not sure how much we can divulge about the campaign but those are safe to remove for now. We'll revisit them should we need them.

**Pull request merged**
